name = "demo-ast1060-rot"
target = "thumbv7em-none-eabihf"
board = "ast1060-rot"
chip = "../../chips/ast1060"
stacksize = 896

[kernel]
name = "demo-ast1060-rot"
requires = {flash = 20000, ram = 3072}

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 2048}
start = true
stacksize = 1536
notifications = ["fault", "timer"]

#[tasks.usart_driver]
#name = "drv-ast1060-usart"
#priority = 2
#max-sizes = {flash = 8192, ram = 1024}
#uses = ["uart1"]
#start = true
#notifications = ["uart1-irq"]
#interrupts = {"uart1.irq" = "uart1-irq"}


[tasks.idle]
name = "task-idle"
priority = 5
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true
