name = "demo-ast1060"
target = "thumbv7em-none-eabihf"
board = "ast1060-dev"
chip = "../../chips/ast1060"
stacksize = 1024
epoch = 0
version = 0

[kernel]
name = "demo-ast1060"
requires = {flash = 32000, ram = 8192}

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 2048}
start = true
stacksize = 1536
notifications = ["fault", "timer"]

[tasks.hmac_hash]
name = "drv-ast1060-hmac-hash-server"
priority = 2
max-sizes = {flash = 16384, ram = 8192}
start = true
stacksize = 4096

[tasks.demo_task]
name = "task-demo-ast1060"
priority = 3
max-sizes = {flash = 16384, ram = 4096}
stacksize = 1024
start = true
task-slots = ["hmac_hash"]
notifications = ["timer"]

[tasks.idle]
name = "task-idle"
priority = 5
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true
