name = "ast1060-starter"
target = "thumbv7em-none-eabihf"
board = "ast1060-rot"
chip = "../../chips/ast1060"
stacksize = 1024 

[kernel]
name = "ast1060-starter"
requires = {flash = 20000, ram = 3072}

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 4096}
start = true
stacksize = 1536
notifications = ["fault", "timer"]

[tasks.i2c]
name = "drv-ast1060-i2c-server"
priority = 3
max-sizes = {flash = 16384, ram = 4096}
stacksize = 2048
start = true
notifications = ["i2c0-irq", "i2c1-irq", "i2c2-irq", "i2c3-irq", "i2c4-irq", "i2c5-irq", "i2c6-irq", "i2c7-irq", "i2c8-irq", "i2c9-irq", "i2c10-irq", "i2c11-irq", "i2c12-irq", "i2c13-irq"]
interrupts = {"i2c0.irq" = "i2c0-irq", "i2c1.irq" = "i2c1-irq", "i2c2.irq" = "i2c2-irq", "i2c3.irq" = "i2c3-irq", "i2c4.irq" = "i2c4-irq", "i2c5.irq" = "i2c5-irq", "i2c6.irq" = "i2c6-irq", "i2c7.irq" = "i2c7-irq", "i2c8.irq" = "i2c8-irq", "i2c9.irq" = "i2c9-irq", "i2c10.irq" = "i2c10-irq", "i2c11.irq" = "i2c11-irq", "i2c12.irq" = "i2c12-irq", "i2c13.irq" = "i2c13-irq"}

[tasks.i2c_client]
name = "task-i2c-client"
priority = 4
max-sizes = {flash = 8192, ram = 2048}
stacksize = 1024
start = true
task-slots = ["i2c"]

[tasks.idle]
name = "task-idle"
priority = 6
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[tasks.uart_driver]
name = "drv-ast1060-uart"
priority = 2
max-sizes = {flash = 8192, ram = 2048}
uses = ["uart"]
start = true
notifications = ["uart-irq"]
interrupts = {"uart.irq" = "uart-irq"}
# task-slots = ["rcc_driver"]

[tasks.helloworld]
name = "task-helloworld"
priority = 5
max-sizes = {flash = 8192, ram = 2048}
uses = ["uart"]
start = true
task-slots = ["uart_driver"]
